### ISSUE TITLE
shorter markdown string

### ISSUE THREAD

**Issue by mfkl** [matthiaszarzecki/UnityBadges#1]
Hi,

Thanks for the nice work, looks cool on readmes :)

Do you think there is a way to have a shorter string? The long string kinda kills the readability of the markdown file, especially if you have many Unity badges.

**Comment by matthiaszarzecki** [comment]
Thanks for reaching out, glad you like the badges so far!

I did some research and turns out the Unity-Logo has been added to the list of available icons in the past, which means the URL can be cut down by 90%, and the image does not need to be encoded in the url anymore.

The new URLs are now in! They look like this, and are much nicer and easier to handle :)

https://img.shields.io/badge/Made%20with-Unity-57b9d3.svg?style=flat&logo=unity

**Comment by mfkl** [comment]
Awesome, thanks!
